---
title: "P1"
author: "Lukas Ji"
date: "2023-09-23"
output:
  pdf_document: default
  html_document: default
class: ALY 6000
---

<CENTER>
<FONT SIZE = 5, color = "red">
<P>
<B>ALY 6000 Introduction to Analytics</B>
<BR>
<B>Lukas Ji</B>
<P>
<B>Date:`r format(Sys.time(), '%d %B, %Y')`</B>
<P>
</FONT>
</CENTER>

```{r setup, include = FALSE, meassage = FALSE, warning = FALSE, echo = FALSE}
cat("\014") # clears console 
rm(list = ls()) # clears global environment 
try(dev.off(dev.list()["RStudioGD"]), silent = TRUE) # clears plots
try(p_unload(p_loaded(), character.only = TRUE), silent = TRUE) # clears packages 
options(scipen = 100) # disables scientific notation for entire R session

library(pacman)
p_load(tidyverse)
p_load(testthat)

first_dataframe <- read.csv("ds_salaries.csv")
```

```{r Q1, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
123 * 453
5^2 * 40
TRUE & FALSE
TRUE | FALSE
75 %% 10
75 / 10
```

```{r Q2, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
first_vector <- c(17, 12, -33, 5)
first_vector
```

```{r Q3, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
counting_by_fives <- c(5, 10, 15, 20, 25, 30, 35)
counting_by_fives
```

```{r Q4, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
second_vector <- seq(10, 30, by=2)
second_vector
```

```{r Q5, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
counting_by_fives_with_seq <- seq(5, 35, by=5)
counting_by_fives_with_seq
```

```{r Q6, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
third_vector <- rep(first_vector, 10)
third_vector
```

```{r Q7, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
rep_vector <- rep(0, 20)
rep_vector
```

```{r Q8, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
fourth_vector <- (10: 1)
fourth_vector
```

```{r Q9, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
counting_vector <-  (5: 15)
counting_vector
```

```{r Q10, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
grades <- c(96, 100, 85, 92, 81, 72)
grades
```

```{r Q11, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
bonus_points_added <- grades + 3
bonus_points_added
```

```{r Q12, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
one_to_one_hundred <- (1:100)
one_to_one_hundred
```

```{r Q13, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
reverse_numbers <- seq(100, -100, -3)
reverse_numbers
```

```{r Q14, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
#Every ele in second_vector add 20
second_vector + 20 
#Every ele in second_vector times 20
second_vector * 20 
#return Boolean result that if each ele in second_vector larger or equal to 20
second_vector >= 20
#return Boolean result that if each ele in second_vector not equal to 20
second_vector != 20 # != means "not equal"
```

```{r Q15, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
total <- sum(one_to_one_hundred)
total
```

```{r Q16, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
average_value <- mean(one_to_one_hundred)
average_value
```

```{r Q17, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
median_value <- median(one_to_one_hundred)
median_value
```

```{r Q18, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
max_value <- max(one_to_one_hundred)
max_value
```

```{r Q19, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
min_value <- min(one_to_one_hundred)
min_value
```

```{r Q20, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
first_value <- second_vector[1]
first_value
```

```{r Q21, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
first_three_values <- second_vector[1:3]
first_three_values
```

```{r Q22, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
vector_from_brackets <- second_vector[c(1, 5, 10, 11)]
vector_from_brackets
```

```{r Q23, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
vector_from_boolean_brackets <- first_vector[c(FALSE, TRUE, FALSE, TRUE)]
vector_from_boolean_brackets #When TRUE means to extract the ele, FALSE means do not extract the ele, that why we extract second and fourth ele in first_vector
```

```{r Q24, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
second_vector >= 20 #return Boolean result that if each ele in second_vector larger or equal to 20
```

```{r Q25, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
ages_vector <- seq(from = 10, to = 30, by = 2) #return a seq start at 10 end at 30 by 2
ages_vector
```

```{r Q26, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
ages_vector [ages_vector >= 20] #return the ele in ages_vector that is larger or equal to 20
```

```{r Q27, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
lowest_grades_removed <- grades[grades >= 85]
lowest_grades_removed
```

```{r Q28, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
middle_grades_removed <- grades[c(-3, -4)]
middle_grades_removed
```

```{r Q29, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
fifth_vector <- second_vector[c(-5, -10)]
fifth_vector
```

```{r Q30, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
set.seed(5) #create reproduced random number
random_vector <- runif(n=10, min = 0, max = 1000) #generate 10 values between 0 and 1000
random_vector
```

```{r Q31, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
sum_vector <- sum(random_vector)
sum_vector
```

```{r Q32, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
cumsum_vector <- cumsum(random_vector)
cumsum_vector
```

```{r Q33, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
mean_vector <- mean(random_vector)
mean_vector
```

```{r Q34, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
sd_vector <- sd(random_vector)
sd_vector
```

```{r Q35, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
round_vector <- round(random_vector)
round_vector
```

```{r Q36, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
sort_vector <- sort(random_vector)
sort_vector
```

```{r Q37, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
set.seed(5) #create reproduced random number
random_vector <- rnorm(n=1000, mean = 50, sd = 15) #generate vector with length 1000 with mean 50 and sd 15
```

```{r Q38, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
hist(random_vector) #we can see that random_vector is a normal distribution with length 1000 mean near 50 sd around 15
```

```{r Q39, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
#read.csv("ds_salaries.csv")
```

```{r Q40, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
p_load(tidyverse)
```

```{r Q41, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
first_dataframe <- read.csv("ds_salaries.csv")
```

```{r Q42, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
#show the first 6 row of the data frame
head(first_dataframe)
#show the first 7 row of the data frame
head(first_dataframe, n = 7)
#show the column names of the data frame
names(first_dataframe)
#set smaller_dataframe as the select columns of the data frame
smaller_dataframe <- select(first_dataframe, job_title, salary_in_usd)
smaller_dataframe #show smaller_dataframe
#set the better_smaller_dataframe as the data frame in order of the selected column
better_smaller_dataframe <- arrange(smaller_dataframe, 
desc(salary_in_usd))
#show better_small_dataframe
better_smaller_dataframe 
#set better_smaller_dataframe as the data frame retaining all rows that satisfy the conditions
better_smaller_dataframe <- filter(smaller_dataframe, salary_in_usd >
80000)
#show better_small_dataframe
better_smaller_dataframe
#creates new columns that are functions of existing variables and modify it *0.94
better_smaller_dataframe <-
 mutate(smaller_dataframe, salary_in_euros = salary_in_usd * .94)
#show better_small_dataframe
better_smaller_dataframe
#index rows by their (integer) locations.
better_smaller_dataframe <- slice(smaller_dataframe, 1, 1, 2, 3, 4, 10, 
1)
#show better_small_dataframe
better_smaller_dataframe
# plot the better_smaller_dataframe, using job-title as x and salary_in_usd as y, fill it with color blue, name x as "Job Title" and y as "Salary in US Dollars",set the title of the graph as "Comparison of Jobs", add dollar sign to y and set the column names of x as angle of 50 and heigh just to 1
ggplot(better_smaller_dataframe) +
 geom_col(mapping = aes(x = job_title, y = salary_in_usd), fill =
"blue") +
 xlab("Job Title") +
 ylab("Salary in US Dollars") +
 labs(title = "Comparison of Jobs ") +
 scale_y_continuous(labels = scales::dollar) +
 theme(axis.text.x = element_text(angle = 50, hjust = 1))
```

```{r test, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
library(pacman)
p_load(testthat)
test_file("project1_tests.R")
```
